concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "eenrame"
  url = "https://gitlab.com/"
  id = 46181945
  token = "t3_zZ_ozGZyVauVJCXeFkbk"
  token_obtained_at = 2025-02-26T11:04:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  environment = ["PATH=C:\\Users\\eenrame\\AppData\\Local\\Programs\\Git\\cmd;C:\\Program Files\\Docker\\Docker\\resources\\bin;${PATH}"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
